### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by PlayxPE** [rico345100/unity-zombie-defense-fps-multiplayer-example#1]
hello, I have a problem, when I shoot with the glock appears a pink png, instead of the "particula" format and I would also like to know if you have like me for this mobile game

**Comment by rico345100** [comment]
Hi, thanks for reporting issue. Could you explain more details about your facing problem?

Generally pink color in Unity appears where something missed or broken, possibly something is wrong with material/texture.

Also the project was tested with 5.6.x versions, so run with later version could be not perfectly compatible.

Please check the texture and material of Glock pistol that has missing reference.

And could you explain your last sentence, sorry I didn't understand.

**Comment by PlayxPE** [comment]
Hi, I'm using google translator so it's going to be difficult to understand, I'm using unity 5.6.5, I'm going to do what you said in the texture problem and the other thing is, if I can turn the game to mobile, I think so , I also wanted to add photon voice

**Comment by rico345100** [comment]
Well, I don't know about Photon Voice. If you need some technical support, you'd better to ask in Photon Forum instead.

**Comment by PlayxPE** [comment]
Ok

**Comment by PlayxPE** [comment]
Hello, I have a question, how can I allow players to kill themselves if they attack each other?

**Comment by rico345100** [comment]
Hi, before help you, questions like this are not issues. Please don't ask advice to implement something here, instead, you better ask to Stackoverflow, especially I recommend GameDev StackExchange: [http://gamedev.stackexchange.com/](http://gamedev.stackexchange.com/), or you can ask me directly to rico345100@gmail.com. 

By default player's doesn't take any damage when they hit. So just add some more script that the object you hit was the player then get reference of Health and invoke method something like TakeDamage(I don't remember exact class name method, you should check out).

Important thing is that how to distinguish it was player. There are many ways to achieve it, I recommend to use Tag something like "Player" or try get reference of script that only Player object has. If script is null then hit object wasn't Player.

```csharp
// Suggestion 1: Using Tags
if(hit.transform.CompareTag("Player")) { ... }

// Suggesion 2: Try get reference
SomeScript someScript = hit.transform.GetComponent<SomeScript>();

if(someScript != null) { ... }    // if this is not null means that it's player
```

BTW, calling GetComponent requires some cost, so I suggest you that using Tag instead. By using CompareTag, you can prevent create some garbage while comparing string with equal operator.

Please close this issue after you read the message. You can freely re-open if you have faced any problem. Thanks.

**Comment by PlayxPE** [comment]
Thanks
